/* poems.js - the poems as they ship with the site (the admin edits them:
   admin -> Poems). Oldest first. Each poem:
     title   also its address on the page (/literature#the-title)
     year    groups the shelf
     color   the book's cover: "auto" (from the palette) or a colour
     text    the poem; a blank line starts a new stanza
     quotes  shown under the poem, one per line
   Converted from poems.html. */

const POEMS = [
  {
    title: "Time, the Silent Thief",
    year: 2024,
    color: "auto",
    quotes: "Time takes nothing all at once—that is how it takes everything.",
    text: "In the quiet passage of time we find,\nA thief unseen, a poison unkind.\nIt steals our days, a slow demise,\nA silent killer in its guise.\n\nTime ages dreams, tears apart hope,\nLeaving behind an echoing slope.\nIt holds in its hands both regret and revenge,\nA cruel master, hard to avenge.\n\nWith power to snatch, to alter and mold,\nLeaving us with tales left untold.\nIt plays with fate, changes the scheme,\nLeaving us adrift in its endless stream.",
  },
  {
    title: "A Dance With Time",
    year: 2024,
    color: "auto",
    quotes: "The past is a closed door; the present is the only key that still turns.",
    text: "The past lies dark, a shadowed door,\nA silent realm of tales no more.\nFor good or ill, it holds its reign,\nA twisted path of joy and pain.\n\nTo tamper there may birth a beast,\nA demon that the past released.\nThe future waits, a realm unseen,\nForged in actions yet unclean.\n\nThe present—fleeting, like a breath,\nA fragile dance with life and death.\nOnce lost, it fades, a ghostly trace,\nNo hand can hold, no will can chase.\n\nAccept the change that time bestows,\nThe seeds of loss, the blooms of woes.\nFor those who fight what's set and done,\nMay lose themselves, their battles won.",
  },
  {
    title: "The Cost of Existence",
    year: 2025,
    color: "auto",
    quotes: "To exist is to lose, to change is to die—yet in every ending, a new path begins.\nTo become something, you must leave something behind.",
    text: "Magic comes at a price, and so does life. Everything you love will fade into the abyss, and one day, you too will disappear into the void.\n\nNothing lasts—not joy, not pain, not even memories. The stars you once wished upon will burn out, the hands you once held will let go, and the voices you cherished will turn to silence.\n\nTo grow is to lose yourself over and over, shedding who you were to become someone new. Every victory demands a sacrifice, every dream costs a part of your soul.\n\nBut does it matter? No.\nBecause even when all is lost, the journey does not end—\nit simply begins again, in the ruins of yesterday.",
  },
  {
    title: "The Empty Road",
    year: 2025,
    color: "auto",
    quotes: "It was never about arriving—it was about what the road burned out of you.",
    text: "Life is a road paved in bone and dust,\nwhere dreams burn like paper, turning to rust.\n\nYou trade your time, your breath, your name,\nchasing a light that flickers the same.\nSome are born with fire, some with chains,\nsome learn too late that loss remains.\n\nThe world takes more than it ever gives,\nhunger and sorrow the cost to live.\nYou reach for something—fame, love, peace—\nonly to watch it slip, piece by piece.\nStill, you run, though the weight is cruel,\nstill, you fight, though you are the fool.\n\nAnd at the end, when feet grow weak,\nwhen silence drowns the words you speak,\nyou'll know the truth, both dark and bright—\nthat life is not about wrong or right.\nIt's about the burn, the fall, the climb,\nabout reaching for more, despite the time.",
  },
  {
    title: "Ashes in the Wind",
    year: 2025,
    color: "auto",
    quotes: "Everything we love is borrowed from time, and time always collects.",
    text: "I loved the trees, their golden crown,\nBut seasons tore their glory down.\nOnce they danced in light so free,\nNow brittle bones of memory.\n\nThe beasts that roared in endless skies,\nNow whispers lost where silence lies.\nOnce they ran with fire untamed,\nNow shadows walk where none are named.\n\nI held their hands, I knew their face,\nBut time is cruel, it leaves no trace.\nTheir laughter faded, soft and thin,\nLike echoes swallowed by the wind.\n\nThe things I built, the songs I knew,\nTurned to dust as moments flew.\nAll I was and all I gave,\nLies nameless in an unmarked grave.\n\nAnd when my breath has left my chest,\nNo hand will hold, no voice attest.\nThe world moves on, the stars still shine,\nBut none will know that it was mine.",
  },
  {
    title: "The Price of the Game",
    year: 2025,
    color: "auto",
    quotes: "Life is borrowed, never won—so spend it like you know that.",
    text: "Life was a debt I never owed,\na weight too heavy, a lie too bold.\nThey sold me dreams at a brutal price,\nbut every breath was an expense of time.\n\nI walked through days that weren't my own,\na hollow face, a voice on loan.\nLove was fleeting, joy was thin,\nand death, you watched—but let me in.\n\nFor in the game of life, death always wins,\nno man outruns the fate he's in.\nThe only choice we're left to make—\nis how to play before we break.\n\nNow here you stand, arms open wide,\nno more farewells, no need to hide.\nNo cost to pay, no mask to keep,\njust endless rest, just quiet sleep.\n\nSo take me back, the game is done,\nlife was borrowed—never won.\nI spent it all, each breath, each year,\nbut death, my friend, you're always near.",
  },
  {
    title: "What's Life, You Ask?",
    year: 2025,
    color: "auto",
    quotes: "Born in light, lost in shadows—such is life.",
    text: "Life's a tragedy, a fleeting curse,\nFrom birth to death, it only gets worse.\nA journey of love, the sweetest sin,\nThat builds a soul—or buries it in.\n\nLove's a gift, or love's a lie,\nIt lifts some up, lets others die.\nFor those who win, it's heaven's grace,\nFor those who lose, a dark embrace.\n\nAnd when love fades,\nthe heart turns stone,\nA hollow shell, lost and alone.\n\nJealous whispers, envy's eyes,\nTurn friends to foes with twisted lies.\n\nSo greed takes root, and wars ignite,\nMen kill for gold, for empty might.\nThey steal, betray, they curse the skies,\nYet rot the same when their body dies.\n\nFor in the end, we all must meet,\nThe death with silent feet.\nNo crown, no love, no time to borrow,\nJust dust, decay, and endless sorrow.",
  },
  {
    title: "Overdose on Yesterday",
    year: 2025,
    color: "auto",
    quotes: "Poison comes in many forms—mine is remembering.",
    text: "Perhaps I'm addicted—\nnot to needles or white lines,\nbut to a hunger that gnaws my bones,\na fire that never dies.\n\nThe sky is cracked, the stars grow cold,\ntime moves, but I stay still.\nChasing echoes, chasing ghosts,\nclimbing walls too steep to will.\n\nThe past is a debt with no clear end,\npaid in restless nights and fraying skin.\nI reach, I fall, I rise again,\nlosing more than I ever win.\n\nA silent hand lingers near,\nwatching, waiting, calm and wise.\nI nod, but turn, one step more—\nI still see gold in ruined skies.",
  },
  {
    title: "The Throne of Ash",
    year: 2025,
    color: "auto",
    quotes: "We reach for heaven and fall like stone, yet we never stop reaching.",
    text: "We build, we break, we rise, we fall,\nWe carve our names on crumbling walls.\nWe chase the stars, yet fear the night,\nWe curse the dark, then hide from light.\n\nWe speak of love, we preach of peace,\nYet wars and hate will never cease.\nWe swear we stand for something great,\nThen bow to gold and call it fate.\n\nWe lift up kings, then tear them down,\nWe trade our thrones for rusted crowns.\nWe drown in dreams we'll never chase,\nThen wonder why we feel misplaced.\n\nWe are the fire, we are the flood,\nBorn from dust, bound by blood.\nWe reach for heaven, fall like stone—\nA world of many, yet alone.\n\nWhat's man apart from war?",
  },
  {
    title: "Left Blank",
    year: 2025,
    color: "auto",
    quotes: "Fate writes the margins; you write the page.",
    text: "I stood beneath a sky heavy with questions, my hands full of broken hours, and I asked, \"If fate has already chosen my road, what use is my struggle, my restless heart?\"\n\nThe weight of days had carved cracks in my chest, my voice was a shadow, thin and fading, yet from the depth of silence, I cried, \"Why do I fight, if the end is already written?\"\n\nAnd then God, calm like dawn after endless night, answered not with thunder, but with quiet light,\n\"Some pages,\" He said, \"I left empty for you, so your hands may fill them with your own fire.\"\n\n\"Walk, even when your knees tremble,\" He told me, \"for the ink of your will is still wet upon the pages.\nNot all is prison, not all is stone—some of your fate waits for you to write it bold.\"",
  },
  {
    title: "The Old Man and the Boy",
    year: 2025,
    color: "auto",
    quotes: "Die only once—not every day before.\nThe quality of a life is born from the quality of its thoughts.",
    text: "There was an old man, bones like dry wood,\neyes like rainclouds that never broke.\nHe sat by the fire, cold though it burned,\nand a young boy came to him, full of life.\n\n\"Old man,\" the boy asked,\n\"why do you watch us so close?\"\n\nThe old man smiled,\na sad, thin smile like dust in the wind.\n\"I am Death,\" he said,\n\"and I watch because you all run so fast,\nbut never see where you are going.\"\n\n\"You pour your heart into the work of your hands,\nyou chase and you climb,\nbut the more you pour, the more you lose.\nYour cups are cracked, boy.\nNo matter how much you fill them,\nthey always leak.\"\n\nThe boy listened,\neyes wide like the sky before rain.\n\"Your life,\" Death said,\n\"is not made by time.\nIt is made by thought.\nA sharp mind makes a rich life.\nBut a dull mind walks in circles,\nand calls it a journey.\"\n\n\"I have buried many,\" Death whispered,\n\"and after many graves, I saw the truth:\nyou are dead long before you lie in the ground.\"\n\n\"You burn with dreams,\nbut your fire turns to ice.\nYou wear love like a coat,\nbut it is never warm enough.\"\n\nThe boy's hands trembled.\n\"And what happens then?\" he asked.\n\nDeath stood,\nslow as the end of a song.\n\"You forget to finish your story,\" he said.\n\"You live like half-written books,\nwaiting for someone else to write the end.\"\n\n\"What you do in life echoes, boy,\nbut even echoes fade.\"\n\nThe fire died between them,\ncold like the old man's voice.\n\n\"So think well,\" Death said,\n\"for the quality of life\nis born from the quality of thought.\"\n\n\"And remember, boy—\"\nhis eyes were graveyards now—\n\"die only once. Not every day before.\"",
  },
  {
    title: "Death and Dance",
    year: 2025,
    color: "auto",
    quotes: "Some scars heal in the dark, others never do.",
    text: "The lights are low, the night is still,\nThe walls are cold, the air is chill.\nBut deep within, a quiet chance—\nA ghostly step, a hidden dance.\n\nThe glass reflects a world once bright,\nNow fading slow in softer light.\nNo voices now, no hurried feet,\nJust silence where the shadows meet.\n\nThe stairs are wide, the path is clear,\nYet no one's left to wander near.\nStill echoes rest on stone and wall,\nAs if they wait for one last call.\n\nA single pole, so tall and white,\nStands like a thought that holds the night.\nIt saw the laughs, the fights, the grace—\nAnd even tears that touched this place.\n\nWe live, we leave, we lose, we find,\nAnd time keeps walking just behind.\nBut in this quiet, don't be blind—\nThe dance of death is soft, not unkind.\n\nSo when you're lost and alone,\nRemember how the wind has blown.\nAnd know that even ends can start—\nFor death, too, has a beating heart.",
  },
  {
    title: "Only You",
    year: 2025,
    color: "auto",
    quotes: "You become what you repeat in silence.\nDiscipline is remembering what you said matters.",
    text: "The world won't hand you anything.\nNot peace. Not truth. Not loyalty.\nIf you don't move—nothing will.\n\nMost people aren't real.\nThey change when you grow.\nThey talk when you win.\nThey liked you better when you were stuck.\n\nSupport is conditional.\n\"Family,\" \"friends,\" even \"loyalty\"—\nAll based on what you give.\nStop giving, and watch them vanish.\n\nSome only speak when there's a crowd.\nSome only feel when there's a screen.\nPain is the new performance.\n\"Struggling\" is a trend.\nYou're not broken—you're loud.\nAnd the loud don't change.\n\nBe the one who disappears to improve.\nLet them wonder where you went.\nLet them whisper.\nBecause no one claps when you're building—\nThey only show up once it's done.\n\nSo stop expecting.\nSilence is the answer.\nWork is the way.\nThe ones who move in quiet\nnever need to explain.",
  },
  {
    title: "The Journey of Realization",
    year: 2025,
    color: "auto",
    quotes: "Change will cost you pieces you didn't plan to lose.",
    text: "Man begins as a herd animal.\nHe obeys, he consumes, he sleeps.\nHe bows before custom,\nand mistakes obedience for wisdom.\nHe does not live—he drifts.\n\nRealization is the revolt.\nIt arrives like lightning in a silent night.\nIt splits the sky of ignorance,\nand shows the raw wound of existence.\nSuffering is not an accident—it is the law.\nTo see it is to bleed with it.\n\nThe weak shut their eyes again.\nThey seek comfort in lies,\nin gods, in nations, in noise.\nBut the strong endure the sight.\nThey do not flee the abyss—\nthey study it, they embrace it.\n\nFrom this embrace comes transformation.\nMan sheds his skin of cowardice.\nHe no longer begs for meaning—\nhe creates it with his own hands.\nHe no longer kneels before sorrow—\nhe becomes the hammer that shatters them.\n\nRealization is not compassion,\nit is not pity, it is not mercy.\nIt is fire that burns illusions,\niron that bends the soul.\nHe who endures it is no longer herd—\nhe becomes changer, destroyer, free spirit.\n\nAnd this is the true journey:\nfrom beast, to blindness, to burden,\nfrom burden, to strength, to freedom.\nNot every man survives it.\nBut those who do—\nare the only ones who have truly lived.",
  },
  {
    title: "Madness Surrounds Us",
    year: 2025,
    color: "auto",
    quotes: "The one who sees the strings is always the one called mad.",
    text: "We promise peace, but start the fight,\nWe act like day, but live in night.\nWe say what's right, but do what's wrong,\nThis gentle madness, all along.\nWe love the comfort of the lie,\nAnd watch the real world pass us by.\n\nThis life is just a circus bright,\nWe dance like puppets, left and right.\nSociety pulls the strings we wear,\nWe're smiling clowns, without a care.\nWe spin and jump, but don't know why,\nBeneath a painted paper sky.\n\nThe one who sees the trick unfold,\nIs called the crazy one, we're told.\nBecause they see the pain and wires,\nTheir lonely heart is what inspires.\nThey see too much, the truth is clear,\nAnd hold that knowledge mixed with fear.\n\nTo break the chain, you must be bold,\nA story waiting to be told.\nAccept the madness, find your ground,\nDon't let your life be pushed around.\nYou are your own, the choice is yours,\nTo find a purpose, open doors.",
  },
  {
    title: "The Beautiful Tragedy",
    year: 2025,
    color: "auto",
    quotes: "It is not time that wounds us, but the memory it leaves behind.",
    text: "What is life but a beautiful tragedy—\na living body that time slowly eats,\ncell by cell, breath by breath,\nuntil the vessel that carried us\nbecomes the very thing we grieve?\n\nI remember evenings when the world paused,\nwhen you and I existed, and nothing else,\nas if the universe conspired\nto hold that single moment\nin its careful, trembling hands.\n\nBut faces fade like photographs left in sunlight.\nIf only I could summon yours once more,\nor know the future well enough\nto change what fate had written—\nbut time wanted you as memory,\nforever untouchable, forever gone.\n\nWhat is time but cruelty incarnate?\nIf it were flesh, I would have killed it first.\nIt steals our happiness like a thief in youth,\ntakes our strength and leaves us brittle,\ncrowns us with maturity we never asked for,\ncalls it wisdom when it's only survival.\n\nTime has no mercy, no ability to preserve—\nit's not time, not youth, but memory\nthat truly wounds us:\nbeautiful, cruel, and desperately important.\n\nFor those who've seen the world without its filter\ncan never fit back into innocence.\nThey've lost the easy ability to smile,\nbecause when you've seen too much,\nyou lose yourself too much—\npiece by piece, like time eating life.",
  },
  {
    title: "Seasons of a Life",
    year: 2025,
    color: "auto",
    quotes: "Some people live long, but never truly exist.",
    text: "The child becomes the youth,\ndrunk on possibility and immortal dreams.\nThe youth becomes the adult,\nlearning that every choice costs something,\nthat love and loss are twins\nborn in the same breath.\n\nThe adult becomes the elder,\ncarrying decades like stones in their pockets,\neach one a story, each one heavy,\nwatching new generations make\nthe same beautiful mistakes.\n\nAnd at the end, we understand:\nwe were never meant to hold forever.\nWe were meant to burn brightly,\nto love fiercely in our moment,\nto leave fingerprints on hearts\nand echoes in the air.\n\nSo live today as if tomorrow is a myth.\nLove with the recklessness of someone\nwho knows it cannot last.\nPreserve this moment in your bones,\nnot in photographs or words,\nbut in the way you breathe it in.\n\nFor tomorrow is cruel, yes—\nbut today is still here,\nstill warm, still possible,\nstill yours to waste or worship.\n\nThe tragedy is not that we die.\nThe tragedy is forgetting to live\nwhile we're still alive.",
  },
  {
    title: "The Sweetness We Carry",
    year: 2025,
    color: "auto",
    quotes: "Time can take the people, never the marks they leave on us.",
    text: "They asked me what life is, and I said life is love,\nand love is a sweet bitter taste on the tongue.\nOn one hand, you hold someone close, feel their warmth,\nand on the other, you watch them slip away like sand.\nDeath, I've learned, is the kindest thief of all—\nat least it doesn't leave you wondering where they went,\nor why they chose to walk a different road without you.\nThere are so many ways to lose people,\nbut time is the cruelest, because it takes them slowly,\npiece by piece, until you can't remember their voice anymore.\n\nTime will pass, as it always does, without permission,\nand you will lose everything—your youth, your dreams,\nthe people you thought would stay forever.\nOne day, you'll even lose yourself,\nbecome someone you don't recognize in the mirror.\nBut here's the strange comfort I've found:\ntime cannot snatch away the marks you leave behind.\nA kindness you showed a stranger on a hard day,\na habit someone picked up just from watching you,\nmaybe even a poem like this one, shared and remembered—\nthese pieces of us remain, woven into other lives,\nlong after we're gone.",
  },
  {
    title: "Echoes in Each Other",
    year: 2025,
    color: "auto",
    quotes: "If you never break, you never really see yourself.",
    text: "Life damages us all, breaks us open in ways we never imagined.\nYou have to be hurt to truly understand what it means to heal,\nto lose in order to know what you once had.\nEvery scar teaches you something—about yourself, about others,\nabout how fragile and fierce the human heart can be.\nWe stumble through our days, collecting wounds and wisdom,\nlearning that pain is just love with nowhere left to go.\nAnd maybe that's the lesson: we're all just trying our best\nwith broken pieces, hoping our cracks let the light in.\n\nSo leave something beautiful behind,\neven if it's small.\nBe kind when the world gives you\nevery reason not to be.\nLove deeply, even knowing it will hurt\nwhen it ends.\nBecause we may leave this world, but\nour parts remain alive—\nin laughter we sparked, in comfort we\ngave, in words we whispered.\nWe are echoes in each other, forever\nand always.",
  },
  {
    title: "Graves Are Quiet; Hearts Are Not",
    year: 2026,
    color: "auto",
    quotes: "Awareness is heavy, but ignorance is a curse.",
    text: "Life moves like a river we cannot hold, carrying moments we cannot name. We search for meaning in work, in love, in fleeting joys, but the current carries us beyond our understanding. To see oneself is to feel both the weight and the flight of existence.\n\nPain is not only a wound; it is the teacher we resist. In loss, in struggle, in nights spent awake with our own thoughts, we confront the parts of ourselves we hide. Awareness is sharp—it cuts and it clears, leaving us raw but alive.\n\nPurpose is not handed to us; it grows from the choices we dare to make, from the risks we bear and the truths we accept. Life tests us in small and great ways, and what we take from it is what we bring to it.\n\nTo live fully is to wrestle with what we cannot control and still step forward. Graves are quiet; hearts are not. The dead rest, but the living carry questions, regrets, and hopes. We are tasked not with escaping existence, but with knowing it, shaping it, and daring to make it ours before the silence finds us.",
  },
  {
    title: "The Uncomfortable Truth",
    year: 2026,
    color: "auto",
    quotes: "Those who see the world without filters are called cold, but perhaps they're the only ones brave enough to look.\nYou don't find meaning in comfort, only in truth.",
    text: "You claim to value truth but silence those who speak it. You say compassion matters, then step over the homeless on your street.\nYou talk about equality while hoarding what you have, sharing only scraps, only leftovers, only what costs you nothing.\n\nMorality shifts like sand beneath your feet—\nfirm when judging others for their failures,\nfluid when explaining away your own.\nYou rewrite the rules each time they inconvenience you.\n\nWatch how quickly principles disappear when survival calls, how love evaporates when it demands real sacrifice, how friendship fades the moment it stops serving your needs.\nWe are merchants, all of us, trading loyalty for advantage.\n\nMaybe this is simply what we are—\ncreatures driven by hunger we've learned to rename, fear we've dressed in reason, emptiness we've tried to fill with noise and bodies and belonging.\n\nWe cling to each other not from love but terror,\nbuild families to escape loneliness,\ncreate societies to hide from our own insignificance,\ninvent meaning because the alternative is unbearable.\n\nSo the question remains unanswered in the silence:\nif we stripped away every pretty word, every noble excuse, if we looked at what we actually do instead of what we say, would we find anything worth saving, or just mirrors reflecting back our own desperate need to matter?",
  },
  {
    title: "The Canvas and the Knife",
    year: 2026,
    color: "auto",
    quotes: "Purpose turns life's horror into art.\nMeaning is made, not found.\nCost of one is another.\nLife gives you the canvas and walks away. What you paint—or refuse to paint—that is your whole story.",
    text: "Life is not a gift, it is raw material.\nHeavy, sharp, unfinished.\nWe are named, shaped, labeled by others first,\nbut art begins the moment we refuse the draft.\n\nBefore vision, there is confusion.\nWe obey without knowing why.\nWe inherit beliefs, routines, fears,\nand call that living.\nThis is the longest stage—and the most dangerous.\n\nThen comes fracture.\nThe moment something feels false.\nThe rules no longer fit,\nthe mask begins to suffocate.\nThis is not freedom yet—\nthis is awareness, and it is painful.\n\nInnocence must die for vision to live.\nOnly then does the canvas reveal itself—\nlight stitched to shadow, beauty born from pain.\nThis world is brutal, and that is why it is real.\n\nWith vision comes responsibility.\nNo one else to blame.\nNo system, no past, no excuse.\nEvery stroke is now chosen,\nand every mistake is owned.\n\nPeople fear death because they never created.\nThey stayed inside lines they didn't draw.\nSo death feels like a judge,\nwhen it is only a mirror.\n\nTo the one who lives on purpose, death is not cruel.\nIt is the frame that gives weight to every stroke.\nKnowing the end is near sharpens the hand.\nMeaning demands an edge.\n\nI live with death close, not as terror but truth.\nIt frees me to choose, to risk, to carve.\nI will fade—but what I shape may remain.\nPurpose is my signature on life.",
  },
  {
    title: "The Bleeding Keys",
    year: 2026,
    color: "auto",
    quotes: "The gap between hoping and knowing—that's your whole life.",
    text: "Imagination is a curse,\na soft lie we tell ourselves\nbefore the world corrects us\nwithout mercy.\n\nThe truth is never kind.\nIt is fire beneath your feet,\nand you walk it anyway\nbecause standing still\nburns worse.\n\nThe rose is beautiful.\nYes.\nBut look closer—\nit is surrounded by thorns,\nand the hands that reach for beauty\nalways bleed.\nThat is not tragedy.\nThat is the price of reaching.\n\nIt is not reality that kills people.\nIt is the distance\nbetween what they imagined\nand what is.\nThat gap—\nthat is where people go to die slowly\nwithout anyone noticing.\n\nOnly when you accept reality\ndo you see it clearly—\ncruelly beautiful,\nhopelessly honest,\na life with no meaning\nhanded to you like an empty canvas\nand a blade instead of a brush.\n\nYou must cut your own meaning into it.\nBleed your own truth onto it.\nGamble everything—\nyour comfort, your belonging, your sleep—\nfor the one purpose\nonly you can name.\nAnd most often,\nthat purpose will make you alone.\n\nHumans are social in theory,\nindividual in the dark.\nIn the practical hours,\nin the 3am hours,\nyou are the only one\ninside your own walls.\n\nImagine it—\na dark room,\nmoonlight,\na window open just enough\nfor the curtains to breathe\nlike something living.\n\nA boy sits in the dark.\nHe has no mouth.\nHe has fear.\nHe has nothing\nbut a piano\nand the silence\npressing against him.\n\nHe plays anyway.\n\nHe bleeds—\nbecause playing without a mouth\nmeans giving what you don't have,\nspending what you cannot spare.\n\nBut he smiles.\nNot because it doesn't hurt.\nBecause it is his hurt.\nHis keys. His bleeding. His music.\n\nAnd before he could reach the\nfinal note—\nlife ended him.\n\nNot the fear.\nNot the pain.\nNot the loneliness.\n\nLife simply\nran out.\n\nThat is the truth no one frames\nand hangs on walls.\n\nYou begin in fear.\nYou find your purpose\nsomewhere in the middle of the fire.\nAnd purpose makes every wound\nworth the bleeding.\n\nBut you do not get to finish.\nNo one does.\n\nIf you end it—\nyou lose the meaning\nyou bled to build.\nYou erase the music\nmid-song.\n\nSo you play.\nBleeding.\nAlone.\nSmiling.\n\nUntil life—\nnot you—\ndecides the last key.\n\nSuch is life.\nCruelly beautiful.\nHopelessly real.\nYours—until it isn't.",
  },
  {
    title: "Of Life and Death",
    year: 2026,
    color: "auto",
    quotes: "Purpose is not what makes life easy. It is what makes death bearable.\nDo not ask life for meaning. Life is the question. You are the answer. Death is the deadline.\nThe beautiful lie of living is that there is still time. Death is simply the moment that lie expires.\nYou were not born to be comfortable. You were born to be spent—on something worthy of the cost.",
    text: "Life is imagination—\na candle lit inside an endless dark.\nBeautiful, yes.\nBut candles burn the hand that holds them\nand devour themselves\nto give light to others.\nThat is not suffering.\nThat is what living costs.\n\nDeath is not the darkness—\nit is the only light that never lies.\nLife decorates itself in colour and warmth,\nwhispering that it will last.\nDeath arrives quietly\nand removes the decoration.\nWhat remains\nis the truth of how you spent yourself.\n\nA life without purpose\nis the most beautiful lie of all—\ncomfortable, painless, and hollow.\nThe wound you carry is not weakness.\nIt is the place where purpose entered you.\nThe rose does not bleed for nothing.\nNeither do you.\nPain with direction\nis not pain.\nIt is the price of becoming.\n\nSo sacrifice.\nGamble everything on what is real.\nFor death is not the tragedy—\narriving at death\nwith nothing spent,\nnothing risked,\nnothing built—\nthat is the tragedy.\nPour yourself out completely.\nLeave nothing\nthat was worth giving.",
  },
  {
    title: "Iron & Silence",
    year: 2026,
    color: "auto",
    quotes: "A knight does not carry his wounds as excuses—he carries them as evidence that he did not stop.\nThe weak man runs toward pleasure because he is running away from himself.\nAt the end it will not matter what you enjoyed—it will matter what you stood for when standing cost everything.\nA knight is not a man without wounds—he is a man who never let his wounds become his reason to stop.\nPleasure is a beautiful thief—it takes your purpose and leaves you smiling at the loss.\nPain does not come to destroy you—it comes to show you what you are made of when everything comfortable is gone.",
    text: "Pain is the forge,\npleasure is the rust,\none builds the blade,\none returns it to dust.\n\nPurpose is the spine—\nwhen it breaks, the man falls,\nnot to the enemy outside\nbut to the comfort in his walls.\nA knight does not fear battle—\nhe fears the day he forgets why he fights,\nthe day pleasure dims his reason\nand he trades his code for nights.\n\nHonor is the marrow—\nit does not show, it holds,\nnot worn for the watching crowd\nbut carried through the cold.\nI keep few people close,\nnot from fear but from truth—\na knight who guards everything\nguards nothing, in the end.\n\nGrief is the river.\nI did not cross it—I drank,\nlet it fill my hollow places,\nlet the weak parts sink and sank.\nWhat the sorrow could not drown\nwas never meant to go,\npain did not destroy me—\nit showed me what I know.\n\nI bleed forward, not backward,\nI kneel only to rise,\nI walk not from the darkness—\nI walk with open eyes.\nNot unbroken—but still standing,\nnot fearless—but still moved,\na knight is not the man who never falls—\nhe is the man that keeps falling but never stops.\n\nAt the end—no crown, no witness,\njust the road, the cross, the cost,\na knight needs no one watching—\nhe walks whether or not he's watched.",
  },
  {
    title: "The Old & The Child",
    year: 2026,
    color: "auto",
    quotes: "Everything rots in the end; the only tragedy is the rose you never reached for.",
    text: "Life asked a child, \"What am I?\"\nThe child turned to the old man.\n\nThe old man said, \"Life is purpose.\"\n\nThe child frowned, \"And what if it isn't?\"\n\nThe old man smiled, slow and heavy:\n\"Then you are not living. You are only surviving.\"\n\nPurpose is a strange beauty.\nLike a rose—soft, red, alive…\nand guarded by thorns.\n\nTo reach it, you will bleed.\nNot once. Not gently.\nAgain and again, until your hands learn pain.\n\nBut listen—\nthe rose does not care for your blood.\nIt waits for the one who is willing to bleed.\n\nBecause that is what purpose is.\nIt does not come to you.\nYou earn the right to see it.\n\nAnd yes—\neven the most beautiful rose will rot one day.\nEverything does.\n\nBut the tragedy is not decay.\nThe tragedy is a man\nwho could have reached the rose…\nand never tried.\n\nObsession—\nthat is the blade.\n\nNot talent. Not luck.\nObsession carves paths where none exist.\n\nIf you can turn pain into creation,\nif you can forge art from your wounds,\nthen what you build will outlive you.\n\nA masterpiece is not made by comfort.\nIt is made by those\nwho refused to stop bleeding.\n\nSo be the one who bleeds for the rose.\n\nBecause such a person has seen truth—\nthe beauty of life,\nthe brutality of effort,\nand the quiet mercy of death.\n\nDeath is a mirror.\nLife is what stands before it.",
  },
  {
    title: "Now We Sharpen It",
    year: 2026,
    color: "auto",
    quotes: "If you treat your goal like an option, it will never become a result.\nObsession starts it. Discipline finishes it.\nGoals don't care how you feel—only what you do.",
    text: "A goal is a blade waiting to be forged.\nCold, useless, just raw metal—\nuntil a man decides to shape it.\n\nObsession is the fire he throws it into.\nNot once, not twice—again and again,\nuntil the metal glows,\nuntil it forgets what it used to be.\n\nDiscipline is the hammer.\nRelentless. Precise.\nStriking the same place,\nover and over,\nuntil form begins to appear.\nIsolation is the forge itself.\nClosed off, burning, unforgiving.\n\nNo one sees the work inside—\nonly the heat,\nonly the noise of steel being made.\nIn the end, the blade is not given.\n\nIt is earned, strike by strike.\nAnd the man who forged in\nis no longer the same metal he began as.",
  },
  {
    title: "Where Beauty Meets Horror",
    year: 2026,
    color: "auto",
    quotes: "Beauty and pain aren't opposites—they grow from the same place.\nDay brings hope. Night brings truth. Only one of them is real.\nChase it forever. It won't come. And when it does—you've forgotten how to feel.",
    text: "Life isn't something you catch.\nThe more you chase it, the more it runs—\nlike water slipping through a closed fist.\n\nYou live in two worlds—\ndaylight hope, midnight truth.\nAnd the space between them isn't empty…\nit's where your life quietly unfolds.\n\nSome people sleep through it.\nMost never question it.\nBut a few wake up—\nand see both edges of existence:\nbeauty that cuts like light,\nhorror that breathes in silence.\nThey don't turn away—they understand.\n\nDeath whispers: anytime.\nNot loud, not cruel—just certain.\nAnd that quiet certainty\nmakes every heartbeat louder.\n\nArt feels haunting because it tells the truth\nwithout hiding behind comfort.\nLife does the same—\nmessy, heavy, unpredictable—\nyet somehow still beautiful in its raw form.\n\nA man doesn't need everything.\nHe needs a reason—\na fire to walk toward,\nor a scar that refuses to fade.\nEither one gives direction.\n\nLove is madness, yes—\nbut not the kind that empties you.\nThe kind that fills you with motion,\nwith meaning, with something real to hold.\n\nSo life isn't about catching or chasing.\nIt's about standing in it—\nfeeling it fully,\neven when it burns.",
  },
  {
    title: "Child and Death",
    year: 2026,
    color: "auto",
    quotes: "Purpose doesn't knock—it grows in what you lose.\nWe come alone, we go alone—everything between is borrowed.\nKindness is real, but it rarely walks alone.",
    text: "\"Maybe I'm wrong,\" the child said,\n\"but kindness, it always wants something.\nNothing in this world feels free.\"\nDeath stood beside him, quiet.\n\n\"Maybe,\" it said, \"but not all wanting is bad.\"\nThe child shook his head,\n\"I think we are alone, like nature.\nWe are born alone,\nand we die alone.\n\nThey say they are one,\nbut I've never seen them together.\"\nDeath gave a small smile,\n\"You never will.\n\nOne comes, then the other follows.\"\nThe child looked into the dark,\n\"Darkness feels honest.\nIt doesn't judge, it just takes.\nAnd when it comes,\nyou only have two choices—\nchange, or regret.\"\n\n\"And if you don't change?\" Death asked.\n\"Then you disappear,\" the child said softly,\n\"like you were never here.\nBut if you do change,\"\nhe paused,\n\"you lose parts of yourself.\nYou become alone,\nlike the dark itself.\"\n\n\"And what does it cost?\"\n\"My heart,\" the child whispered.\nThe wind passed between them.\n\"Nothing is fair,\" the child went on,\n\"for something to begin,\nsomething must end.\n\nThat's how it always works.\"\nDeath nodded slowly,\n\"And how do you find purpose?\"\nThe child looked up, eyes tired,\n\"When you lose something\nimportant,\n\nsomething that breaks you a little.\nThat's when it starts.\"\nDeath turned to leave,\n\"Then you already understand.\"\nThe child stayed there,\nnot afraid, just quiet,\nholding the weight of his own\nthoughts.",
  },
  {
    title: "The Weight of Wanting",
    year: 2026,
    color: "auto",
    quotes: "If you keep stepping back, don't expect to ever move forward.\nWin or lose—at least make it clear you gave everything.\nA life without risk feels safe, but slowly turns empty inside.",
    text: "Most men carry bread.\nI have been carrying a sun\nin both hands,\nwondering why I am always\nburning.\n\nThe possible is a cage\nbuilt by the probable.\nI have measured its bars.\nI have also measured\nthe space between them.\n\nI am still deciding\nwhich measurement matters.\n\nHere is what I know about time—\nit does not wait for the ready man.\nIt waits for no man at all.\nAnd so the question\nwas never \"when.\"\n\nThe question was always\n\"who dares to begin\nbefore they are ready.\"\n\nA stone dropped in water\ndoes not ask permission\nto make waves.\n\nIt simply\nfalls\nwith everything it has\nand lets the water\ndecide\nwhat to do\nwith the disturbance.\n\nBe the stone.\n\nThe horizon is a lie\nthe earth tells the eye—\n\"this far, no further,\nhere is where the world ends.\"\n\nAnd yet the sailor\nwho believed the horizon\nnever found the new world.\n\nEvery true thing\nwas discovered\nby someone\nwho refused\nthe last border.\n\nI have sat with doubt.\nWe have had long dinners together,\ndoubt and I.\nIt is honest company.\nIt asks hard questions.\nIt finishes my wine.\n\nBut doubt has never once\nbuilt anything.\n\nThey will tell you\nto be reasonable.\n\nReason is a tool.\nA good one.\nA necessary one.\n\nBut the house of reason\nhas no room\nfor the things most worth having.\n\nLove is not reasonable.\nBeauty is not reasonable.\nAnd every idea\nthat ever cracked the world open\nand let the light in—\n\nwas, at first,\ncompletely,\nmagnificently\n\"unreasonable.\"\n\nThe dream is not escape.\n\nThe dream is the only place\nI have ever felt\nfully awake—\nstanding in it\nlike a man standing in rain,\nsoaked through,\ncold,\nalive\nin every single nerve.\n\nWhat is a man\nwithout the thing\nhe would suffer for?\n\nHe is comfortable.\nHe is sensible.\nHe sleeps well\nand wakes to nothing\npulling at him,\nnothing unfinished\nburning in the corner\nof every room he enters.\n\nHe is safe.\n\nAnd safety,\nwithout something at stake,\nis just\na long\nslow\ndisappearing.\n\nSo I choose the fire.\n\nNot because I am brave—\nI am not brave.\nI am simply more afraid\nof becoming\n\"less\"\nthan I am afraid\nof being\n\"burned.\"\n\nThe impossible thing\nmay never come.\n\nI have made peace with that\nthe way the river\nmakes peace with the rock—\n\nnot by surrendering,\n\nbut by deciding\nto go around it,\nover it,\nthrough it\nif necessary—\n\nand to keep\nthe sound of moving water\nas long\nas there is\nany water\nleft.\n\nThis is not optimism.\nOptimism is easy.\nThis is something older.\nSomething without a clean name.\n\nIt is the thing in a man\nthat kneels in the dark\nand still\nplants a seed—\n\nnot because he knows\nit will grow,\n\nbut because\nhe is still,\nafter everything,\n\"human enough\nto try.\"",
  },
  {
    title: "What Death Cannot Take",
    year: 2026,
    color: "auto",
    quotes: "Meaning isn't given to you—you shape it by what you carry.",
    text: "\"A man owns only the present;\ndeath takes only the moment he lives in.\"\n\nThe past survives as a cemetery of memory,\nthe future drifts like smoke beyond reach.\nBetween them stands the human soul—\nfragile as glass,\nyet stubborn enough to search for meaning in chaos.\n\nMost people dissolve into the gravity of the crowd,\nallowing borrowed thoughts to shape borrowed lives.\nBut the mind was never meant for quiet submission;\nit was meant to carve its own philosophy\nagainst the stone walls of existence.\n\nPurpose is not discovered like treasure beneath the earth.\nIt is forged inwardly—\nthrough solitude, suffering, reflection,\nand the courage to remain different.\n\nA river does not ask the mountain for permission to flow,\nand the stars do not compete to justify their light.\nThey simply exist as themselves.\n\nSo sharpen your intellect against doubt,\nwalk beyond the comfort of imitation,\nand become the author of your own existence.\n\nBecause when death finally arrives,\nit cannot take the truths you awakened to—\nonly the final second in which you carried them.",
  },
  {
    title: "The Price of Tomorrow",
    year: 2026,
    color: "auto",
    quotes: "The life you want is hiding in what you avoid.\nWhat you refuse to face becomes your master.",
    text: "Where am I supposed to go?\nTo the past?\n\nThe past is a room full of broken mirrors.\nEvery piece shows a mistake,\nevery reflection asks a question I cannot answer.\n\nTo the future?\n\nThe future is a shadow standing at the end of a long road.\nI know it is there,\nbut I do not know whether it holds a crown or a coffin.\nOr should I stay here?\n\nIn the present.\nThis place they call a gift,\nyet it feels more like a nightmare.\n\nA nightmare with a face.\nAnd that face is mine.\n\nFor who else knows my weaknesses better than me?\nWho else whispers doubt into my ear when the world is silent?\nWho else stands between the life I want and the life I live?\n\nTell me—\n\nIs suffering a punishment,\nor is it the hammer that shapes a man?\nIs regret a chain,\nor is it a map showing where not to walk again?\n\nIf the future is truly in my hands,\nwhy do I fear holding it?\n\nMaybe the past is not chasing me.\nMaybe I am the one carrying it.\nMaybe the future is not frightening.\nMaybe I am afraid of what I must become to reach it.\n\nSo the question remains:\nWill I suffer now and build something greater?\n\nOr will I run from the pain,\nonly to find it waiting beside my grave?\n\nAnd when my story ends,\nwill my scars speak of battles fought,\n\nor opportunities buried?",
  },
  {
    title: "A Conversation With Time",
    year: 2026,
    color: "auto",
    quotes: "Slow is not stopped—the hand still reaches every hour.",
    text: "I looked at a clock\nuntil my mind became as empty\nas the space between its ticks.\n\nThe hand moved forward.\n\nOnly forward.\n\nSo slowly\nthat movement seemed impossible,\nyet when I looked again,\nit had already left\nwhere it once stood.\n\nIsn't that how life passes?\n\nNot in storms,\nnot in grand moments,\nbut in silent seconds\nthat never return.\n\nThe clock never hurries.\nIt never competes.\nIt never asks\nwhether it is ahead or behind.\n\nStill,\nit reaches every hour.\n\nPerhaps that is the secret:\nthe river reaches the sea\nnot because it rushes,\nbut because it never stops flowing.\n\nAnd when the day is done,\nthe clock returns to one.\n\nNot because time repeats,\nbut because beginnings\nwear the face of endings.\n\nEvery midnight buries a day.\nEvery dawn resurrects another.\n\nTwenty-four hours—\nan entire lifetime for a day—\ngone,\nand born again.\n\nWe are not so different.\n\nEach morning\nwe wake as someone\nslightly new,\ncarrying yesterday's dust\ninto tomorrow's light.\n\nThe clock teaches this quietly:\n\nMove forward.\n\nEven if no one notices.\nEven if the distance is small.\nEven if all you have\nis a single step.\n\nFor time never moves backward,\nand neither does life.\n\nAnd one day,\nwithout asking permission,\nthe hands will stop.\n\nThe ticking will fade.\n\nThe circle will remain,\nbut the journey will be over.\n\nUntil then,\n\nbe like the clock—\n\nnot fast,\nnot loud,\n\njust faithful\nto the next second.",
  },
  {
    title: "The Distance Between Desire and Peace",
    year: 2026,
    color: "auto",
    quotes: "The river reaches the sea; only man chases a horizon that walks away.",
    text: "I asked the river,\n\"Why do you hurry?\"\n\nIt laughed against the stones.\n\n\"I do not hurry.\nThe sea is simply\nthe shape of my nature.\"\n\nThen I asked the old tree,\n\"Why do you stand so still\nwhile the world runs?\"\n\nThe tree shed a leaf.\n\n\"Because running and arriving\nare the same thing\nto those who become dust.\"\n\nSo I turned to my own heart.\n\nIt spoke no word.\n\nDay after day\nit desired,\nobtained,\nand desired again.\n\nThen I understood:\n\nThe river reaches the sea.\nThe tree reaches the earth.\n\nOnly man\nreaches for horizons\nthat retreat with every step.\n\nAnd calls this hunger\nhis life.\n\nEverything in nature fulfills its nature effortlessly, but humans are trapped by endless desire.",
  },
  {
    title: "You Must Walk",
    year: 2026,
    color: "auto",
    quotes: "Purpose is built where comfort is killed.",
    text: "Let your heart burn, if it must—\nlike a dying star swallowing itself,\nlet your flesh turn cold, stone-bound,\nlet your will crack like glass in winter.\nLet every voice fade, every hand release,\nlet love be torn from your ribs—\nbut still,\nwalk.\nOn broken feet, drag your shadow.\nWith bloodied steps, carve your vow.\nDie again, and again, and again,\nuntil death forgets your name.\n\nThe stars you wished on are ash now.\nThe sky does not remember your prayers.\nWhat you were will rot beneath your skin—\nshed it.\nTo become is to bleed.\nTo dream is to die for it.\nEach breath is a sacrifice,\neach victory, a funeral for who you were.\nBut if one ember remains,\nyou guard it—\nas if the world still lives inside it.\n\nAnd when all is silent—walk.\nEven through the bones of yesterday.\nEven if you are the last soul screaming.\nGod does not crown the comfortable.\nHe crowns the broken,\nthe betrayed,\nthe ones who walk with nothing but ruin\nin their hands—\nand still dare to leave a legacy\nwhere others left only dust.",
  },
];

export default POEMS;
